#!/bin/sh
export PYTHON_PATH=../../root
scripts=../../scripts
outfile=../tool-usage.txt
echo > $outfile

echo "#######################################################################" >> $outfile
echo "#  recon tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/recon --help >> $outfile
echo >> $outfile

#echo "#######################################################################" >> $outfile
#echo "#  fdf2img tool usage:">> $outfile
#echo "#######################################################################" >> $outfile
#$scripts/fdf2img >> $outfile
#echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  getparam tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/getparam --help >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  dumpheader tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/dumpheader --help >> $outfile
echo >> $outfile

