To build this library:

gcc -g -c *.c -O
ar -rv libhunwrap.a *.o
ranlib libhunwrap.a

When Compiling code using this library link using:

 -L./Hussein_Unwrap  -lhunwrap

The file Unwrap.c contains the function unwrap_phs which has prototype:

  unwrap_phs(pwr, puw, n_pe, n_fe, n_slice)

The input and out put data are 3D data arranged within a 1D array.
