#!/usr/bin/env python
"""
Program: epi_recon, Read data from fid, take FFT, and write to disk.

One of the first chores of recon_epi is to organize the data into a conventional 
ordering of the data so that various operations may be performed upon the data 
in a manner independent of the order of collection of the phase-encode lines of 
data.

Because Python does not allow indices of arrays (or lists) to start at negative 
values the convention in recon_epi is to number the phase-encode lines as 0 
through 2N-1 where we assume there are 2N phase encode lines (2N = n_pe_true). 
With this convention the phase-encode gradient has zero magnitude at line N-1. 
The following diagram makes this convention clear for the first and second slices 
within a volume (block) of slices:


                        Recon_epi Line Numbering Convention
                       ===================================== 

       recon_epi line                                        k-space k_pe value
      ----------------                                      --------------------

         ^                             ^
         |                    :        |        :
         |                    :        |        :
         |                    :        |        :                                
          \ ____                       | 
          /                            |
         | 4N - 1  <-------------------|------------------->  k_pe = N*del_k
         |                             |
         | 4N - 2  <-------------------|------------------->  k_pe = (N-1)*del_k
         |                    :        |        :
         |                    :        |        :
         |                    :        |        :
         |   N     <-------------------|------------------->  k_pe = del_k
         |                             |
slice 1 -| N - 1   <-------------------|------------------->  k_pe = 0
         |                             |
         | N - 2   <-------------------|------------------->  k_pe = -del_k
         |                    :        |        :
         |                    :        |        :
         |                    :        |        :
         | 2N + 1  <-------------------|------------------->  k_pe = -(N-2)*del_k
         |                             |
         |   2N    <-------------------|------------------->  k_pe = -(N-1)*del_k
          \___                         |
          /                            |
         | 2N - 1  <-------------------|------------------->  k_pe = N*del_k
         |                             |
         | 2N - 2  <-------------------|------------------->  k_pe = (N-1)*del_k
         |                    :        |        :
         |                    :        |        :
         |                    :        |        :
         |   N     <-------------------|------------------->  k_pe = del_k
         |                             |
slice 0 -| N - 1   <-------------------|------------------->  k_pe = 0
         |                             |
         | N - 2   <-------------------|------------------->  k_pe = -del_k
         |                    :        |        :
         |                    :        |        :
         |                    :        |        :
         |   1     <-------------------|------------------->  k_pe = -(N-2)*del_k
         |                             |
         |   0     <-------------------|------------------->  k_pe = -(N-1)*del_k
          \___                         |
                                       |
                                       v


The phase-encode-tables used by recon_epi are created by hand from the scanner-
vendor's phase-encode-table files. While we could use the vendors phase-encode-
tables directly a coding simplification is acheived by using our own file format 
for the phase-encode-tables. Since this need be done only once it is of no great 
cost given benefits. The recon_epi phase-encode-table files are stored in a 
directory named "tablib" under the recon.varian package.

The different vendors will store their phase-encode tables in different system 
directories. The Varian scanner has the phase-encode tables stored in a directory 
named tablib. 
"""
from recon.tools.Recon import Recon
#if __name__ == "__main__": Recon().run()
import pdb
if __name__ == "__main__": pdb.run('Recon().run()')


