#!/bin/sh
export PYTHONPATH=../../root
scripts=../../scripts
outfile=../tool-usage.txt
echo > $outfile

echo "#######################################################################" >> $outfile
echo "#  recon tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/recon --help >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  fdf2img tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/fdf2img >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  getparam tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/getparam --help >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  dumpheader tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/dumpheader --help >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  viewimage tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/viewimage --help >> $outfile
echo >> $outfile

echo "#######################################################################" >> $outfile
echo "#  imaging-doc tool usage:">> $outfile
echo "#######################################################################" >> $outfile
$scripts/imaging-doc --help >> $outfile
echo >> $outfile

